#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8793
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSPS.AppFramework.DBModule
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="ZHOSPS")]
	public partial class T_TrunkNoRecognitionRecordDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public T_TrunkNoRecognitionRecordDataContext() : 
				base(global::OSPS.AppFramework.DBModule.Properties.Settings.Default.ZHOSPSConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public T_TrunkNoRecognitionRecordDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public T_TrunkNoRecognitionRecordDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public T_TrunkNoRecognitionRecordDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public T_TrunkNoRecognitionRecordDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<T_TrunkNoRecognitionRecord> T_TrunkNoRecognitionRecord
		{
			get
			{
				return this.GetTable<T_TrunkNoRecognitionRecord>();
			}
		}
	}
	
	[Table(Name="dbo.T_TrunkNoRecognitionRecord")]
	public partial class T_TrunkNoRecognitionRecord
	{
		
		private string _F_TrunkNo;
		
		private System.Nullable<System.DateTime> _F_EnterTime;
		
		private string _F_State;
		
		private string _F_ImageIndex;
		
		public T_TrunkNoRecognitionRecord()
		{
		}
		
		[Column(Storage="_F_TrunkNo", DbType="VarChar(20)")]
		public string F_TrunkNo
		{
			get
			{
				return this._F_TrunkNo;
			}
			set
			{
				if ((this._F_TrunkNo != value))
				{
					this._F_TrunkNo = value;
				}
			}
		}
		
		[Column(Storage="_F_EnterTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> F_EnterTime
		{
			get
			{
				return this._F_EnterTime;
			}
			set
			{
				if ((this._F_EnterTime != value))
				{
					this._F_EnterTime = value;
				}
			}
		}
		
		[Column(Storage="_F_State", DbType="VarChar(10)")]
		public string F_State
		{
			get
			{
				return this._F_State;
			}
			set
			{
				if ((this._F_State != value))
				{
					this._F_State = value;
				}
			}
		}
		
		[Column(Storage="_F_ImageIndex", DbType="VarChar(20)")]
		public string F_ImageIndex
		{
			get
			{
				return this._F_ImageIndex;
			}
			set
			{
				if ((this._F_ImageIndex != value))
				{
					this._F_ImageIndex = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
